server:
  port: 7900
spring:
  application:
    name: provider-user
  #热部署
  devtools:
    restart:
      enabled: true
      trigger-file: devtools.tg
eureka:
  client:
    #registerWithEureka: false
    #fetchRegistry: false
    serviceUrl:
      defaultZone: http://user:123456@localhost:8761/eureka/
  instance:
    prefer-ip-address: true      #显示ip