server:
  port: 8762
  #因为当前的eureka是单机的，所以我们需要加一些配置
eureka:
  client:
    # 是否把自己作为服务注册到其他服务注册中心
    #registerWithEureka: false
    # 是否从其他的服务中心同步服务列表
    #fetchRegistry: false
    serviceUrl:
      #defaultZone: http://user:123@${eureka.instance.hostname}:${server.port}/eureka/
      #defaultZone: http://user:123@localhost:10001/eureka/
      defaultZone: http://user:123456@peer1:8761/eureka/,http://user:123456@peer3:8763/eureka/
  instance:
    hostname: peer2
spring:
  security:
    user:
      name: user
      password: 123456
  application:
    name: eurekaServerHigh
  profiles:
    active: peer2
